import oracledb

# 오라클 연결 함수
def get_connection():
    try:
        connection = oracledb.connect(
            user="c##colorwalk",             # 오라클 사용자명
            password="walk123",    # 오라클 SYSTEM 계정 비밀번호
            dsn="localhost:1521/XE"    # XE 버전 기본 주소
        )
        return connection
    except Exception as e:
        print("❌ Oracle 연결 실패:", e)
        return None


# (선택) 초기 테이블 생성
def init_db():
    conn = get_connection()
    if conn:
        cur = conn.cursor()
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE photo (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR2(50),
                        color VARCHAR2(20),
                        description VARCHAR2(500),
                        location VARCHAR2(200),
                        image_path VARCHAR2(300),
                        likes NUMBER DEFAULT 0,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE = -955 THEN NULL; -- 이미 존재하면 무시
                    ELSE RAISE;
                    END IF;
            END;
        """)
        conn.commit()
        cur.close()
        conn.close()
        print("✅ Oracle 테이블 준비 완료")
    else:
        print("❌ DB 연결 실패로 테이블 생성 중단")
