import oracledb

# ✅ Oracle Connection Pool 생성
pool = oracledb.create_pool(
    user="system",             # 사용자명
    password="1234",           # 비밀번호
    dsn="localhost:1521/XE",   # XE 기본 주소
    min=2,                     # 최소 연결 유지 개수
    max=5,                     # 최대 연결 개수
    increment=1,               # 늘어나는 단위
    timeout=60,                # 유휴 연결 유지 시간(초)
)

# ✅ 연결 함수 (기존과 동일하게 사용 가능)
def get_connection():
    try:
        connection = pool.acquire()  # 풀에서 즉시 연결 가져오기
        return connection
    except Exception as e:
        print("❌ Oracle 연결 실패:", e)
        return None


# ✅ 초기 테이블 생성
def init_db():
    conn = get_connection()
    if conn:
        cur = conn.cursor()
        try:
            cur.execute("""
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE photo (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR2(50),
                            color VARCHAR2(20),
                            description VARCHAR2(500),
                            location VARCHAR2(200),
                            image_path VARCHAR2(300),
                            likes NUMBER DEFAULT 0,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    ';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE = -955 THEN NULL; -- 이미 존재하면 무시
                        ELSE RAISE;
                        END IF;
                END;
            """)
            conn.commit()
            print("✅ Oracle 테이블 준비 완료")
        except Exception as e:
            print("⚠️ 테이블 생성 중 오류:", e)
        finally:
            cur.close()
            conn.close()
    else:
        print("❌ DB 연결 실패로 테이블 생성 중단")
